#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/victorcoder/dkron"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

# dkron depends on and uses an older version of go-hclog
# which does not have `StandardWriter` as part of the hclog.Logger
# interface. Hence, if using a newer version of hclog, an error 
# occurs specifying that dkron.HCLogAdapter does not implement the
# new hclog.Logger interface.
# Lock on a previous version of go-hclog (as specified and used by dkron)
[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "61d530d6c27f994fb6c83b80f99a69c54125ec8a"
